### PR TITLE
feat: add monitoring terms to context #2094

### PR DESCRIPTION
**Pull request by HoucemKacem**
Terms as Alert, category, validFrom and validTo already exists in https://fiware.github.io/data-models/context.jsonld, but I added them as well.

### CODE REVIEW

**Comment by AHABID** [comment]
To keep some homogeneity between Alerts and Anomalies maybe defining both of them is better than keeping Alert on Fiware context and defining new URI for the Anomalie.

**Comment by bobeal** [comment]
> To keep some homogeneity between Alerts and Anomalies maybe defining both of them is better than keeping Alert on Fiware context and defining new URI for the Anomalie.

And to have then in separated and not mixed with the pure irrigation context (easier later to remove them and switch to the core smart data models context)

**Comment by HoucemKacem** [comment]
> And to have then in separated and not mixed with the pure irrigation context (easier later to remove them and switch to the core smart data models context)

I added `smartIrrigationMonitoring.jsonld `, let me know if the filename should be changed.

**Comment by bobeal** [comment]
> > And to have then in separated and not mixed with the pure irrigation context (easier later to remove them and switch to the core smart data models context)
> 
> I added `smartIrrigationMonitoring.jsonld `, let me know if the filename should be changed.

The points is that it contains terms related to alerts and anomalies, and not to irrigation. So I would just call it alertAndAnomaly.jsonld

**Review by bobeal — APPROVED** [review]

**Review by AHABID — APPROVED** [review]

**Pull request merged**
